import { OrderModel } from "../models";
export const listOrders: OrderModel[] = [
  {
    id: "1",
    imgProduct: "Shirt_1.jpg",
    nameProduct: "Pink Shirt",
    salePrice: 250,
    retailPrice: 250,
    description:
      "Pink Shirt Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cumque at blanditiis nulla eveniet sapiente nobis exercitationem, facilis nemo, ipsum ea ratione nesciunt architecto consequatur, repudiandae doloremque minima a inventore numquam.  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cumque at blanditiis nulla eveniet sapiente nobis exercitationem, facilis nemo, ipsum ea ratione nesciunt architecto consequatur, repudiandae doloremque minima a inventore numquam.",
    type: "Shirt",
    quantity: 5,
  },
  {
    id: "2",
    imgProduct: "Shirt_2.jpg",
    nameProduct: "White Shirt",
    salePrice: 250,
    retailPrice: 250,
    description: "White Shirt",
    type: "Shirt",
    quantity: 5,
  },
  {
    id: "3",
    imgProduct: "Shirt_3.jpg",
    nameProduct: "Black Shirt",
    salePrice: 250,
    retailPrice: 250,
    description: "Black Shirt",
    type: "Shirt",
    quantity: 5,
  },
  {
    id: "4",
    imgProduct: "Pant_1.jpg",
    nameProduct: "Black Pant",
    salePrice: 250,
    retailPrice: 250,
    description: "Black Pant",
    type: "Pant",
    quantity: 5,
  },
  {
    id: "5",
    imgProduct: "Pant_2.jpg",
    nameProduct: "Brown Pant",
    salePrice: 250,
    retailPrice: 250,
    description: "Brown Pant",
    type: "Pant",
    quantity: 5,
  },
  {
    id: "6",
    imgProduct: "Shirt_1.jpg",
    nameProduct: "Pink Shirt",
    salePrice: 250,
    retailPrice: 250,
    description: "Pink Shirt",
    type: "Shirt",
    quantity: 5,
  },
  {
    id: "7",
    imgProduct: "Shirt_2.jpg",
    nameProduct: "White Shirt",
    salePrice: 250,
    retailPrice: 250,
    description: "White Shirt",
    type: "Shirt",
    quantity: 5,
  },
  {
    id: "8",
    imgProduct: "Shirt_3.jpg",
    nameProduct: "Black Shirt",
    salePrice: 250,
    retailPrice: 250,
    description: "Black Shirt",
    type: "Shirt",
    quantity: 5,
  },
  {
    id: "9",
    imgProduct: "Pant_1.jpg",
    nameProduct: "Black Pant",
    salePrice: 250,
    retailPrice: 250,
    description: "Black Pant",
    type: "Pant",
    quantity: 5,
  },
];
